build-development:
    image: docker:19.03.13
    stage: build
    services:
        - docker:19.03.13-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f Dockerfile --tag $CI_REGISTRY_IMAGE:latest-development .
        - docker push $CI_REGISTRY_IMAGE:latest-development
    only:
        - main
