stages:
    - build
    - deploy
    - cleanup

build-development:
    image: docker:19.03.13
    stage: build
    services:
        - docker:19.03.13-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f Dockerfile --tag $CI_REGISTRY_IMAGE:latest-development .
        - docker push $CI_REGISTRY_IMAGE:latest-development
    only:
        - main

deploy-development:
    image:
        name: bitnami/kubectl
        entrypoint: ['']
    stage: deploy
    script:
        - kubectl rollout restart deployment game-scrabble-backend-dev --namespace=capgemini
    only:
        - main

cleanup-development:
    image: ubuntu
    stage: cleanup
    script:
        - apt-get update && apt-get install -y curl
        - curl -v -X POST https://backend-dev.capgemini.enl-projects.com/rooms/sync-rooms-in-game-backend/scrabble
        - sleep 2
    only:
        - main
